-- Create the role if it doesn't exist
CREATE ROLE IF NOT EXISTS terragrunt_role;

-- Global account-level privileges
GRANT CREATE DATABASE         ON ACCOUNT TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT CREATE WAREHOUSE        ON ACCOUNT TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT CREATE ROLE             ON ACCOUNT TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT APPLY MASKING POLICY    ON ACCOUNT TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT CREATE INTEGRATION      ON ACCOUNT TO ROLE terragrunt_role WITH GRANT OPTION;

-- Grant role to Terraform user
GRANT ROLE terragrunt_role TO USER github_ci_user;

-- Usage and object-level privileges (with grant option)
GRANT USAGE ON DATABASE NORTHWIND_DB_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT USAGE ON SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;

-- External integrations access
GRANT USAGE ON STAGE NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV.S3_STAGE_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE NORTHWIND_WH_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT USAGE ON INTEGRATION S3_INTEGRATION_DEV TO ROLE terragrunt_role WITH GRANT OPTION;

-- Future grants (auto-provisioning)
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;

-- Transfer schema ownership (ensures full control)
GRANT OWNERSHIP ON SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role REVOKE CURRENT GRANTS;

-- Restore privileges after ownership transfer
GRANT USAGE ON DATABASE NORTHWIND_DB_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT USAGE ON SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA NORTHWIND_DB_DEV.NORTHWIND_SCHEMA_DEV TO ROLE terragrunt_role WITH GRANT OPTION;
