version: 2

sources:
  - name: external_tables
    database: NORTHWIND_DB_DEV
    schema: NORTHWIND_SCHEMA_DEV
    tables:
      - name: mart_sales_external
        description: "External table created from S3"
      - name: mart_customer_sales_external
        description: "External table created from S3"
      - name: mart_product_sales_external
        description: "External table created from S3"
      - name: mart_employee_performance_external
        description: "External table created from S3"
      - name: mart_sales_by_region_external
        description: "External table created from S3"
      - name: mart_sales_by_country_year_external
        description: "External table created from S3"

models:
  - name: mart_sales
    columns:
      - name: link_order_product_key
        description: "Unique identifier for the order-product relationship."

      - name: hub_order_key
        description: "Business key representing the order."
        meta:
          pii: true
          sensitivity: critical

      - name: hub_product_key
        description: "Business key representing the product."
        meta:
          pii: true
          sensitivity: critical

      - name: order_date
        description: "The date the order was placed."
        meta:
          pii: true
          sensitivity: critical

      - name: shipped_date
        description: "The date the order was shipped."
        meta:
          pii: true
          sensitivity: critical

      - name: freight
        description: "Shipping cost associated with the order."

      - name: unit_price
        description: "Price of a single unit at the time of sale."

      - name: quantity
        description: "Number of units ordered."

      - name: discount
        description: "Discount applied to this order line."

      - name: revenue
        description: "Net revenue for the line item after applying discount."
        tests:
          - not_null

      - name: line_load_ts
        description: "Timestamp when the satellite record was last loaded."

      - name: line_record_source
        description: "Indicates the system or process that provided this data."

  - name: mart_customer_sales
    columns:
      - name: company_name
        description: "Name of the company."
        meta:
          pii: true
          sensitivity: critical

      - name: country
        description: "Country of the company."

      - name: hub_customer_key
        description: "Business key representing the customer."
        meta:
          pii: true
          sensitivity: critical

      - name: link_order_product_key
        description: "Unique identifier for the order-product relationship."

      - name: load_ts
        description: "Timestamp when the satellite record was last loaded."

      - name: revenue
        description: "Net revenue for the line item after applying discount."

  - name: mart_employee_performance
    columns:
      - name: hub_employee_key
        description: "Business key representing the employee."
        meta:
          pii: true
          sensitivity: critical

      - name: total_lines
        description: "Total number of lines processed by the employee."

      - name: total_revenue
        description: "Total revenue generated by the employee."

  - name: mart_product_sales
    columns:
      - name: hub_product_key
        description: "Business key representing the product."

      - name: total_orders
        description: "Total number of orders for the product."

      - name: total_quantity
        description: "Total quantity of the product sold."

      - name: total_revenue
        description: "Total revenue generated by the product."

  - name: mart_sales_by_country_year
    columns:
      - name: order_count
        description: "Total number of orders for the country in the given year."

      - name: ship_country
        description: "Country where the orders were shipped."

      - name: total_freight
        description: "Total freight cost for the country in the given year."

      - name: total_revenue
        description: "Total revenue generated for the country in the given year."

      - name: year
        description: "The year associated with the sales data."
  - name: mart_sales_by_region
    columns:
      - name: month
        description: "The month associated with the sales data."

      - name: order_count
        description: "Total number of orders for the region in the given month."

      - name: ship_city
        description: "City where the orders were shipped."

      - name: ship_country
        description: "Country where the orders were shipped."

      - name: ship_region
        description: "Region where the orders were shipped."

      - name: total_freight
        description: "Total freight cost for the region in the given month."

      - name: total_revenue
        description: "Total revenue generated for the region in the given month."
